/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package games;

import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 1094260
 */
public class Cubo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cubo.class.getName());

    /**
     * Creates new form Cubo
     */
    public Cubo() {
        initComponents();
    }
    public void sorteio (){
        Random r = new Random();
        int sorte = r.nextInt(7);
        
        String c = "";
        
        switch (sorte) {
            case 0:
                int sorteZero = r.nextInt(2);
                if (sorteZero == 0) {
                    c = "/Img/explosao3.gif";
                    JOptionPane.showMessageDialog(null, "Você jogou o dado com força!!!");
                }else if (sorteZero == 1) {
                    c = "/Img/explosao2.gif";
                    JOptionPane.showMessageDialog(null, "Você jogou o dado com força!!!");
                }
                break;
            case 1:
                c = "/Img/dado1.png";
                break;
            case 2:
                c = "/Img/dado2.png";
                break;
            case 3:
                c = "/Img/dado3.png";
                break;
            case 4:
                c = "/Img/dado4.png";
                break;
            case 5:
                c = "/Img/dado5.png";
                break;
            case 6:
                c = "/Img/dado6.png";
                break;
            default:
                throw new AssertionError();
        }
        URL url = getClass().getResource(c);
        if (url != null) {
            ImageIcon imagemOriginal = new ImageIcon(url);
            Image imagem = imagemOriginal.getImage().getScaledInstance(
                    300,
                    300,
                    Image.SCALE_DEFAULT);
            jlbponto.setIcon(new ImageIcon(imagem));
        }else{
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao lançar o dado");
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtJogar = new javax.swing.JButton();
        jlbponto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dado");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbtJogar.setText("Jogar ");
        jbtJogar.addActionListener(this::jbtJogarActionPerformed);

        jlbponto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dice-roll-dice.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbponto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jbtJogar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jlbponto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtJogar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtJogarActionPerformed
        sorteio();
        
        
    }//GEN-LAST:event_jbtJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cubo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtJogar;
    private javax.swing.JLabel jlbponto;
    // End of variables declaration//GEN-END:variables
}
